export const UPDATE_SHAPE_UNITS_COUNT = "UPDATE_SHAPE_UNITS_COUNT";
export const UPDATE_GRID = "UPDATE_GRID";
export const START_DROP_NEW_BLOCK = "START_DROP_NEW_BLOCK";
export const STOP_DROP_NEW_BLOCK = "STOP_DROP_NEW_BLOCK";
